name: "Determine Runner for Jobs"
description: "Checks the status of self-hosted runners and selects a runner based on availability."
author: "@BenjaminMichaelis"
branding:
  icon: "check-circle"
  color: "green"

inputs:
  primary-runner:
    description: "The labels of the self-hosted runner."
    required: true
  fallback-runner:
    description: "The runner to use if the primary runner is not available."
    required: true
  github-token:
    description: "The GitHub token."
    required: true

outputs:
  use-runner:
    description: "The runner to be used for subsequent jobs."

runs:
  using: 'composite'
  steps:
    - run: |
        # Extract the organization name
        org=${{ github.repository }}
        org=${org%%/*}

        # Fetch the list of repository runners
        response=$(gh api repos/${{ github.repository }}/actions/runners --jq '.runners[] | select(.status=="online" and .busy==false and (.labels[].name | contains("${{ inputs.primary_runner }}")) )')

        # If no runners are returned for the repository, check at the organization level
        if [ -z "$response" ]; then
          response=$(gh api orgs/$org/actions/runners --jq '.runners[] | select(.status=="online" and .busy==false and (.labels[].name | contains("${{ inputs.primary_runner }}")) )')
        fi

        # Check if the response is not null before setting the output
        if [ -n "$response" ]; then
          echo "::set-output name=runner::${{ inputs.primary_runner }}"
        else
          echo "::set-output name=runner::${{ inputs.fallback_runner }}"
        fi
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}